# Generated by Django 5.2.1 on 2025-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("technologies", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("preview_image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("stack", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("preview_image_url", models.URLField()),
                ("project_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
